### ISSUE TITLE
Incomplete and incorrect vcf headers

### ISSUE THREAD

**Issue by wdecoster** [haojingshao/npInv#4]
Hi,

I'm using v1.21 and notice the following:

- The chromosomes/contigs are not defined in the header - leading to errors with e.g. bcftools
- The following header lines are apparently not according to the vcf specifications:

```
##arguments: --input ../ngmlr_alignment/NA19240.bam --output ngmlr-npInv.vcf
##method: npInv1.21
```

Changing these to the following fixed the errors (again from bcftools).

```
##arguments=--input ../ngmlr_alignment/NA19240.bam --output ngmlr-npInv.vcf
##method=npInv1.21
```

Cheers,
Wouter

**Comment by haojingshao** [comment]
Hi Wdecoster,

Sorry for the late reply. I update the code to 1.22 and likely fix the format problem. Thank you for letting me know.

Cheers,
Haojing

**Comment by wdecoster** [comment]
Hi Haojing,

Thanks for the fix - npInv is a great tool. But I don't think your update (not sure - don't know java) fixes the first part of my issue:

- The chromosomes/contigs are not defined in the header - leading to errors with e.g. bcftools

I don't know if I will have the time soon to test the new version.

Cheers,
Wouter

**Comment by haojingshao** [comment]
Hi Wdecoster,

I have added the "contig" field in the vcf header and tested bcftools (version 1.3, function bcftools query and bcftools stats). It works without errors. 

Cheers,
Haojing

**Comment by wdecoster** [comment]
Great, thanks a lot!
