### ISSUE TITLE
Adding to bioconda: please create release and add license 

### ISSUE THREAD

**Issue by wdecoster** [haojingshao/npInv#5]
Hi,

I would like to add npInv to bioconda, but for this I need you to:
- create a release of the latest version allowing me to use a stable url
- add a license to your repo

Thanks in advance,
Wouter

**Comment by haojingshao** [comment]
HI Wouter,

I add a release. See link https://github.com/haojingshao/npInv/releases/download/1.23/npInv1.23.jar.
I also add a MIT license.

cheers,
Haojing

**Comment by wdecoster** [comment]
Hi Haojing,

Thanks a lot. I'll see how hard or easy this is :-)
One more thing, I would need a command for npInv to know that it's working, a test. That could be a real test with input and output files, but often just `--help` or `-h` is enough to see that it executes without errors. It seems npInv has no such help command to get the usage? When executing `java -jar ~/npInv/npInv1.22.jar --help` I get an error (No Key Name: output) followed by the usage information. The problem with this is that the return code of this error is 1, while a test would require an error code of 0.

Thanks,
Wouter

**Comment by haojingshao** [comment]
Hi Wouter,

This is a very good suggestion. I add the "help" usage and it will return 0. This may help you steaming this program. Is there anything else to improve?

Cheers,
Haojing

**Comment by wdecoster** [comment]
Thanks! I think this should be sufficient. I'll let you know if we encounter anything else.

**Comment by wdecoster** [comment]
I just merged the new recipe into bioconda and it will be available soon.
